spring.application.name=eureka-server
server.error.include-message=always
server.error.include-binding-errors=always
#Dichiaro la porta del server
server.port=8761

#Impedisco al server di autoregistrarsi
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

#Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
