spring.application.name=eureka-server

#Dichiaro la porta del server
server.port=8671

#Impedisco al server di autoregistrarsi
eureka.client.fetch-registry=false
eureka.client.registry-with-eureka=false